### ISSUE TITLE
Bulk Export

### ISSUE THREAD

**Issue by mwgreen00** [colemanja91/pyeloqua#32]
I can't export two CDOs in a row.  The first one will export fine.  When I run the second one, it throws an error saying the fields don't match the CDO.  It returns the fields for the first CDO and not the second one I'm working on.  I am able to overcome the issue by resetting the bulk object: bulk = Bulk(company=myCompany, username=myUserName, password=myPassword) and running the second export again.

Is this be design or an issue?

**Comment by colemanja91** [comment]
It's hard to tell without seeing more of the code. 
You could try resetting the bulk object by running `bulk.reset()` between exports; that'll reset everything to beginning state, so you'll need to redefine your fields, filters, etc (which you would need to do anyway). 

The original idea was that in a production system, a task would be limited to one import or export per python script, which keeps the code more readable and maintainable.

**Comment by mwgreen00** [comment]
Bulk.reset() works perfectly.  Thank you for the feedback.

**Comment by colemanja91** [comment]
Cool!
