### ISSUE TITLE
Adding Contact Fields When Exporting CDO Data via Bulk Export

### ISSUE THREAD

**Issue by mwgreen00** [colemanja91/pyeloqua#33]
How do I add contact object fields when exporting CDO data via Bulk Export?

**Comment by colemanja91** [comment]
```python
bulk.exports(elq_object='customobjects', obj_id=123)
bulk.add_linked_fields(lnk_obj='contacts', field_input=['C_EmailAddress', 'C_FirstName', 'C_LastName'])
```

Also works for adding contact fields to events exports, and adding account fields to contact exports.

**Comment by mwgreen00** [comment]
Perfect.  It worked.  Thank you for the help.
